import Image from 'next/image';
import Link from 'next/link';
import { Search, ChevronRight, ArrowRight, Play, CarFront, BadgeCheck, Banknote, Headphones, ShieldCheck, MapPin, Phone, Star } from 'lucide-react';
import { getCars, getTestimonials } from '@/lib/api';

const filters: Array<[string, string[]]> = [
  ['Make', ['All Makes', 'Toyota', 'BMW', 'Volkswagen', 'Ford', 'Mercedes-Benz']],
  ['Model', ['All Models', 'Golf', 'Polo', 'Ranger', 'X3', 'D-Max']],
  ['Vehicle Type', ['All Types', 'SUV', 'Sedan', 'Bakkie', 'Hatchback', 'Coupe']],
  ['Year', ['All Years', '2026', '2025', '2024', '2023', '2022']],
  ['Colour', ['All Colours', 'Black', 'White', 'Silver', 'Grey', 'Blue']],
  ['Max Price', ['Under R200 000', 'R200 000 – R400 000', 'R400 000 – R600 000', 'R600 000 – R800 000', 'R800 000+']],
];

const benefits = [
  { Icon: BadgeCheck, title: 'Quality vehicles', copy: 'Carefully selected pre-owned stock' },
  { Icon: Banknote, title: 'Finance made easy', copy: 'Simple, guided application support' },
  { Icon: Headphones, title: 'Friendly service', copy: 'A team ready to help you buy with confidence' },
  { Icon: CarFront, title: 'Wide selection', copy: 'Cars for city, family, work and adventure' },
];

export default async function Home() {
  const cars = await getCars();
  const globalTestimonials = await getTestimonials();
  const newArrivals = cars.slice(0, 6);
  const categories = [
    { name: 'SUVs', copy: 'A perfect blend of comfort, space, and presence for every lifestyle.', type: 'SUV', image: '/SUVs.png' },
    { name: 'Coupes', copy: 'Sleek, stylish, and built for speed with dynamic performance.', type: 'Coupe', image: '/Coupes.png' },
    { name: 'Bakkies', copy: 'Rugged durability and powerful capability, ready for work or weekend.', type: 'Bakkie', image: '/Bakkies.png' },
    { name: 'Hatchbacks', copy: 'Convenient, efficient and fun to drive for everyday life.', type: 'Hatchback', image: '/Hatchbacks.png' },
  ];
  const makes = [
    { name: 'Hyundai', image: '/hyundia-1536x664.png' },
    { name: 'Lexus', image: '/lexus.png' },
    { name: 'Mercedes-Benz', image: '/mers-1536x1536.png' },
    { name: 'Nissan', image: '/nissan-1536x1308.png' },
    { name: 'Toyota', image: '/toy.png' },
    { name: 'Volkswagen', image: '/vw-1536x1533.png' },
  ];

  return (
    <div className="min-h-screen overflow-hidden bg-[#282828] text-white">
      <section className="relative min-h-[650px] overflow-visible bg-black sm:min-h-[690px] lg:min-h-[720px]">
        <Image src="https://icargezina.co.za/wp-content/uploads/2025/05/1003_14989_I1.jpg" alt="Vehicles inside the ICar Gezina showroom" fill priority referrerPolicy="no-referrer" className="object-cover object-center" />
        <div className="absolute inset-0 bg-black/48" />
        <div className="absolute inset-0 bg-gradient-to-b from-black/50 via-black/15 to-black/70" />
        <div className="absolute inset-x-0 bottom-0 h-40 bg-gradient-to-t from-[#282828] to-transparent" />
        <div className="relative z-10 mx-auto flex min-h-[650px] max-w-7xl items-center justify-center px-4 pb-24 pt-28 text-center sm:min-h-[690px] sm:px-6 lg:min-h-[720px] lg:px-8">
          <div className="max-w-5xl">
            <p className="text-xs font-semibold uppercase tracking-[0.32em] text-white/75">ICar Gezina</p>
            <h1 className="mt-4 text-5xl font-extrabold leading-[1.04] tracking-[-0.045em] sm:text-6xl lg:text-[64px]">Find the car of your dreams at <span className="block">ICar Gezina</span></h1>
            <p className="mx-auto mt-6 max-w-5xl text-sm leading-7 text-white/75 sm:text-base">At ICar Gezina, we make car buying simple, affordable, and enjoyable. Explore our wide range of quality vehicles and take advantage of our easy, on-site finance options. With friendly service, expert advice, and a streamlined process, getting behind the wheel has never been easier.</p>
          </div>
        </div>

        <section className="absolute inset-x-4 bottom-[-74px] z-30 sm:inset-x-6 lg:inset-x-8">
          <div className="mx-auto max-w-7xl overflow-hidden rounded-xl border border-white/15 bg-[#171717]/95 shadow-[0_24px_70px_rgba(0,0,0,0.45)] backdrop-blur-xl">
            <div className="grid grid-cols-1 gap-2 p-4 sm:grid-cols-2 sm:p-5 lg:grid-cols-3 xl:grid-cols-[repeat(6,minmax(0,1fr))_auto]">
              {filters.map(([label, options]) => <select key={label} aria-label={label} className="h-12 w-full border-0 border-b border-[#E8751A]/70 bg-transparent px-4 text-xs font-medium text-white/75 outline-none transition focus:border-[#E8751A] focus:ring-0 [&>option]:bg-[#303030] [&>option]:text-white"><option value="">{label}</option>{options.map(option => <option key={option} value={option}>{option}</option>)}</select>)}
              <Link href="/cars" className="flex h-12 items-center justify-center rounded-lg bg-[#16A6B8] px-7 text-xs font-semibold text-white transition hover:bg-[#1192A2]">Search</Link>
            </div>
          </div>
        </section>
      </section>

      <div className="h-24 bg-[#282828]" />

      <section className="bg-[#282828] py-20 sm:py-24 lg:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-10 flex items-end justify-between gap-6 sm:mb-12"><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#F28A2E]">Latest stock</p><h2 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">New Arrivals</h2><p className="mt-3 max-w-xl text-sm text-white/45">Freshly added vehicles ready for their next owner.</p></div><Link href="/cars" className="hidden items-center gap-2 rounded-full border border-white/15 px-5 py-2.5 text-xs font-bold sm:inline-flex hover:border-[#16A6B8] hover:text-[#16A6B8]">View all <ArrowRight className="h-3.5 w-3.5" /></Link></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{newArrivals.map(car => <Link href={`/cars/${car.id}`} key={car.id} className="group overflow-hidden rounded-2xl border border-white/10 bg-[#303030] transition duration-300 hover:-translate-y-1 hover:border-white/20 hover:shadow-2xl hover:shadow-black/20"><div className="relative aspect-[4/3] overflow-hidden bg-black"><Image src={car.imageUrl} alt={`${car.make} ${car.model}`} fill unoptimized referrerPolicy="no-referrer" className="object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-transparent to-transparent" /><span className="absolute left-4 top-4 rounded-full bg-black/60 px-3 py-1.5 text-[9px] font-bold uppercase tracking-wider backdrop-blur">{car.year}</span><span className="absolute bottom-4 right-4 rounded-full bg-[#16A6B8] px-3 py-1.5 text-[9px] font-bold uppercase tracking-wider">View vehicle</span></div><div className="p-5"><p className="text-[10px] font-semibold uppercase tracking-wider text-white/35">{car.mileage.toLocaleString()} km • {car.bodyType}</p><h3 className="mt-2 min-h-12 text-lg font-bold leading-tight">{car.make} {car.model}</h3><div className="mt-5 flex items-end justify-between gap-3 border-t border-white/10 pt-4"><span className="text-2xl font-black text-white">R {car.price.toLocaleString()}</span><ChevronRight className="h-5 w-5 text-[#16A6B8] transition group-hover:translate-x-1" /></div></div></Link>)}</div><div className="mt-8 text-center sm:hidden"><Link href="/cars" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-5 py-3 text-xs font-bold">View all vehicles <ArrowRight className="h-4 w-4" /></Link></div></div></section>

      <section className="bg-[#303030] py-20 sm:py-24"><div className="mx-auto grid max-w-7xl gap-5 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div className="group relative min-h-[460px] overflow-hidden rounded-2xl"><Image src={newArrivals[0]?.imageUrl || 'https://picsum.photos/seed/showroom/1200/800'} alt="ICar Gezina showroom" fill unoptimized referrerPolicy="no-referrer" className="object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/25 to-black/5" /><div className="absolute bottom-0 left-0 right-0 p-7 sm:p-9"><p className="text-[10px] font-bold uppercase tracking-[0.24em] text-[#F28A2E]">Welcome to ICar Gezina</p><h2 className="mt-2 text-3xl font-black sm:text-4xl">Explore our showroom</h2><p className="mt-3 max-w-lg text-sm leading-6 text-white/65">Discover a wide selection of quality vehicles. If we don't have what you're looking for, let our team know and we'll help find it.</p><Link href="/cars" className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#16A6B8] px-6 py-3 text-xs font-bold transition hover:bg-[#1192A2]">View showroom <ArrowRight className="h-4 w-4" /></Link></div></div><div className="relative overflow-hidden rounded-2xl border border-white/10 bg-[#242424] p-7 sm:p-9"><div className="absolute right-0 top-0 h-56 w-56 rounded-full bg-[#16A6B8]/10 blur-3xl" /><div className="relative flex h-full flex-col"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#16A6B8]/15 text-[#16A6B8]"><Banknote className="h-7 w-7" /></div><div className="mt-auto pt-20"><p className="text-[10px] font-bold uppercase tracking-[0.24em] text-[#F28A2E]">Easy on-site finance</p><h2 className="mt-2 text-3xl font-black sm:text-4xl">Get behind the wheel sooner.</h2><p className="mt-4 max-w-lg text-sm leading-7 text-white/55">Our streamlined finance application process makes it simple to move from browsing to driving, with friendly guidance along the way.</p><div className="mt-7 grid grid-cols-3 gap-3 border-y border-white/10 py-5"><div><ShieldCheck className="h-4 w-4 text-[#16A6B8]" /><p className="mt-2 text-[10px] uppercase tracking-wider text-white/40">Guided</p></div><div><Banknote className="h-4 w-4 text-[#16A6B8]" /><p className="mt-2 text-[10px] uppercase tracking-wider text-white/40">Convenient</p></div><div><Headphones className="h-4 w-4 text-[#16A6B8]" /><p className="mt-2 text-[10px] uppercase tracking-wider text-white/40">Personal</p></div></div><Link href="/finance" className="mt-7 inline-flex w-fit items-center gap-2 rounded-full border border-white/20 px-6 py-3 text-xs font-bold transition hover:border-[#16A6B8] hover:text-[#16A6B8]">Apply for finance <ArrowRight className="h-4 w-4" /></Link></div></div></div></div></section>

      <section className="bg-[#282828] py-20 sm:py-24 lg:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-10 max-w-3xl sm:mb-12"><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#F28A2E]">Find your style</p><h2 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">The right car for your lifestyle.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/50 sm:text-base">From rugged bakkies and spacious SUVs to sporty coupes and practical hatchbacks, discover a vehicle built around the way you live.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category, index) => <Link href={`/cars?bodyType=${encodeURIComponent(category.type)}`} key={category.name} className="group overflow-hidden rounded-[24px] border border-white/10 bg-[#202020] shadow-[0_18px_45px_rgba(0,0,0,0.22)] transition duration-500 hover:-translate-y-2 hover:border-white/20 hover:shadow-[0_28px_70px_rgba(0,0,0,0.4)]"><div className="relative aspect-[4/3] overflow-hidden bg-[#171717]"><Image src={category.image} alt={`${category.name} vehicles`} fill unoptimized sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 25vw" className="object-contain p-3 transition duration-700 ease-out group-hover:scale-[1.03]" /><div className="absolute inset-0 bg-gradient-to-t from-black/20 via-transparent to-transparent pointer-events-none" /><div className="absolute left-4 top-4 flex h-9 w-9 items-center justify-center rounded-full border border-white/20 bg-black/35 text-[10px] font-bold text-white/80 backdrop-blur-md">0{index + 1}</div><div className="absolute right-4 top-4 flex h-9 w-9 items-center justify-center rounded-full border border-white/15 bg-black/30 text-white/70 backdrop-blur-md transition duration-300 group-hover:border-[#16A6B8]/70 group-hover:bg-[#16A6B8] group-hover:text-white"><ArrowRight className="h-4 w-4 -rotate-45 transition duration-300 group-hover:rotate-0" /></div></div><div className="p-6 sm:p-7"><div className="mb-4 h-px w-10 bg-[#E8751A] transition-all duration-500 group-hover:w-16" /><h3 className="text-2xl font-black tracking-tight sm:text-[26px]">{category.name}</h3><p className="mt-2 text-sm leading-6 text-white/60">{category.copy}</p><div className="mt-5 flex items-center justify-between border-t border-white/10 pt-4"><span className="text-[10px] font-bold uppercase tracking-[0.18em] text-white/45">Browse {category.name}</span><span className="text-xs font-bold text-[#16A6B8] transition group-hover:text-white">Explore</span></div></div></Link>)}</div></div></section>

      <section className="border-y border-white/10 bg-[#242424]"><div className="mx-auto grid max-w-7xl divide-y divide-white/10 px-4 sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4 lg:px-8">{benefits.map(({ Icon, title, copy }) => <div key={title} className="flex gap-4 px-4 py-7 sm:px-6 lg:px-8"><Icon className="mt-0.5 h-5 w-5 shrink-0 text-[#16A6B8]" /><div><h3 className="text-sm font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-white/40">{copy}</p></div></div>)}</div></section>

      <section className="bg-[#303030] py-20 sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-10 text-center sm:mb-12"><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#F28A2E]">Browse by make</p><h2 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">Explore our vehicles</h2><p className="mx-auto mt-3 max-w-xl text-sm text-white/45">Choose a trusted make and discover the vehicles currently available at ICar Gezina.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{makes.map(make => <Link key={make.name} href={`/cars?make=${encodeURIComponent(make.name)}`} className="group relative overflow-hidden rounded-2xl border border-white/10 bg-[#282828] shadow-[0_16px_45px_rgba(0,0,0,0.2)] transition duration-500 hover:-translate-y-1 hover:border-white/20 hover:shadow-[0_24px_60px_rgba(0,0,0,0.35)]"><div className="relative aspect-[16/8] overflow-hidden bg-white"><Image src={make.image} alt={`${make.name} vehicles`} fill unoptimized sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-contain p-5 transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/10 via-transparent to-transparent" /></div><div className="flex items-center justify-between gap-4 p-5"><div><p className="text-[9px] font-bold uppercase tracking-[0.2em] text-[#F28A2E]">Make</p><h3 className="mt-1 text-xl font-black">{make.name}</h3></div><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-white/10 text-white/60 transition group-hover:border-[#16A6B8] group-hover:bg-[#16A6B8] group-hover:text-white"><ArrowRight className="h-4 w-4" /></span></div></Link>)}</div><div className="mt-9 text-center"><Link href="/cars" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#16A6B8] transition hover:text-white">See all vehicles <ArrowRight className="h-4 w-4" /></Link></div></div></section>

      <section className="bg-[#282828] py-20 sm:py-24 lg:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-10 flex flex-col justify-between gap-5 sm:mb-12 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#F28A2E]">Happy customers</p><h2 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">What our customers say</h2></div><div className="flex items-center gap-2 text-xs text-white/40"><Star className="h-4 w-4 fill-[#F28A2E] text-[#F28A2E]" /> Real customer experiences</div></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{globalTestimonials.slice(0, 6).map(testimonial => <article key={testimonial.id} className="rounded-2xl border border-white/10 bg-[#303030] p-6 transition hover:border-white/20"><div className="flex gap-1 text-[#F28A2E]">{[...Array(5)].map((_, i) => <Star key={i} className="h-3.5 w-3.5 fill-current" />)}</div><p className="mt-5 text-sm leading-7 text-white/65">“{testimonial.content}”</p><div className="mt-6 border-t border-white/10 pt-4"><p className="text-sm font-bold">{testimonial.author}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-white/35">{testimonial.role}</p></div></article>)}</div></div></section>

      <section className="bg-[#303030] py-20 sm:py-24"><div className="mx-auto grid max-w-7xl items-center gap-10 px-4 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:px-8"><div className="relative min-h-[390px] overflow-hidden rounded-2xl bg-black"><Image src={newArrivals[1]?.imageUrl || newArrivals[0]?.imageUrl || 'https://picsum.photos/seed/icar/1200/800'} alt="ICar Gezina vehicle" fill unoptimized referrerPolicy="no-referrer" className="object-cover" /><div className="absolute inset-0 bg-black/35" /><div className="absolute inset-0 flex items-center justify-center"><div className="flex h-20 w-20 items-center justify-center rounded-full bg-[#16A6B8] shadow-2xl shadow-black/30"><Play className="ml-1 h-8 w-8 fill-white" /></div></div><div className="absolute bottom-5 left-5 rounded-full border border-white/15 bg-black/45 px-4 py-2 text-[9px] font-bold uppercase tracking-[0.18em] backdrop-blur">The ICar Gezina experience</div></div><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#F28A2E]">Simple. Affordable. Enjoyable.</p><h2 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">More than buying a car.</h2><p className="mt-5 text-sm leading-7 text-white/50">We believe buying a vehicle should feel straightforward and personal. From your first search to finance, delivery and after-sales support, our team is here to make the journey easier.</p><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/10 bg-[#282828] p-4"><MapPin className="h-4 w-4 text-[#16A6B8]" /><p className="mt-3 text-xs font-bold">Visit us in Gezina</p></div><div className="rounded-xl border border-white/10 bg-[#282828] p-4"><Phone className="h-4 w-4 text-[#16A6B8]" /><p className="mt-3 text-xs font-bold">Talk to our team</p></div></div><Link href="/contact" className="mt-7 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 text-xs font-bold text-[#282828] transition hover:bg-white/90">Contact ICar Gezina <ArrowRight className="h-4 w-4" /></Link></div></div></section>

      <section className="relative overflow-hidden bg-[#E8751A] py-16 sm:py-20"><div className="absolute -right-20 -top-32 h-80 w-80 rounded-full bg-white/10 blur-3xl" /><div className="relative mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-black/45">Looking for your next vehicle?</p><h2 className="mt-2 text-4xl font-black tracking-tight text-white sm:text-5xl">Let's get you moving.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-white/75">Explore our current stock or speak with our team about finding the right vehicle for you.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/cars" className="inline-flex items-center gap-2 rounded-full bg-[#282828] px-6 py-3 text-xs font-bold text-white">Browse showroom <ArrowRight className="h-4 w-4" /></Link><Link href="/contact" className="inline-flex items-center gap-2 rounded-full border border-white/40 px-6 py-3 text-xs font-bold text-white">Contact us</Link></div></div><div className="rounded-2xl border border-white/20 bg-black/10 p-6 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-black/45">Want to sell or trade?</p><h3 className="mt-2 text-2xl font-black text-white">We can help with that too.</h3><p className="mt-3 text-sm leading-6 text-white/70">Talk to ICar Gezina about your current vehicle and explore your options for selling or trading in.</p><Link href="/contact" className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-white underline decoration-white/40 underline-offset-4">Start a conversation <ArrowRight className="h-4 w-4" /></Link></div></div></section>
    </div>
  );
}
