'use client'

import { GripVertical, Image as ImageIcon, ImagePlus, Link2, Plus, Star, Trash2, ArrowUp, ArrowDown } from 'lucide-react'
import { useState } from 'react'

type GalleryManagerProps = { value: string[]; onChange: (value: string[]) => void }
function isValidUrl(url: string) { return /^https?:\/\/[^\s]+$/i.test(url.trim()) }

export function GalleryManager({ value, onChange }: GalleryManagerProps) {
  const [draft, setDraft] = useState('')
  const [error, setError] = useState('')
  const [failedImages, setFailedImages] = useState<string[]>([])
  function add() { const url = draft.trim(); if (!url) return; if (!isValidUrl(url)) { setError('Enter a valid image URL beginning with http:// or https://.'); return }; if (value.includes(url)) { setError('This image is already in the gallery.'); return }; onChange([...value, url]); setDraft(''); setError('') }
  function move(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= value.length) return; const next = [...value]; [next[index], next[target]] = [next[target], next[index]]; onChange(next) }
  function remove(index: number) { const url = value[index]; onChange(value.filter((_, i) => i !== index)); setFailedImages(current => current.filter(item => item !== url)) }
  return <div className="space-y-6">
    <div className="rounded-2xl border border-[#e5e7eb] bg-[#f8fafc] p-5 sm:p-6">
      <div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#e8f7f9] text-[#16A6B8]"><ImagePlus size={19}/></div><div><h4 className="text-sm font-bold text-[#1f2937]">Build your vehicle gallery</h4><p className="mt-1 max-w-xl text-xs leading-5 text-[#6b7280]">Add your best photography, then arrange it into a story customers can follow. The first image becomes the lead photo.</p></div></div>
      <div className="mt-5 flex flex-col gap-3 sm:flex-row"><div className="min-w-0 flex-1"><div className="relative"><Link2 className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9ca3af]"/><input id="gallery-image-url" value={draft} onChange={e => setDraft(e.target.value)} onKeyDown={e => { if(e.key==='Enter'){e.preventDefault();add()} }} placeholder="Paste an image URL…" className="h-12 w-full rounded-xl border border-[#d1d5db] bg-white pl-10 pr-4 text-sm outline-none focus:border-[#16A6B8] focus:ring-2 focus:ring-[#16A6B8]/10" /></div>{error && <p className="mt-2 text-xs font-medium text-red-600">{error}</p>}</div><button type="button" onClick={add} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-[#282828] px-5 text-xs font-bold text-white hover:bg-black"><Plus size={15}/> Add photo</button></div>
    </div>
    <div className="flex items-center justify-between gap-3"><div><h4 className="text-sm font-bold text-[#1f2937]">Vehicle media</h4><p className="mt-1 text-xs text-[#6b7280]">{value.length ? `${value.length} photos · First photo is the lead image` : 'No photos added yet'}</p></div>{value.length > 0 && <span className="rounded-full bg-[#eef8f9] px-3 py-1.5 text-[11px] font-bold text-[#128b7a]">{value.length} / 20</span>}</div>
    {value.length === 0 ? <div className="rounded-2xl border border-dashed border-[#cfd4da] bg-white px-6 py-14 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#f3f4f6] text-[#9ca3af]"><ImageIcon size={24}/></div><h4 className="mt-4 text-sm font-bold text-[#374151]">Start the vehicle story</h4><p className="mx-auto mt-1 max-w-md text-xs leading-5 text-[#6b7280]">Add exterior, interior and detail photography. Use your strongest front three-quarter image first.</p></div> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{value.map((url,index)=>{const failed=failedImages.includes(url);return <article key={`${url}-${index}`} className={`group overflow-hidden rounded-2xl border bg-white ${index===0?'border-[#16A6B8] ring-2 ring-[#16A6B8]/10':'border-[#e5e7eb]'}`}><div className="relative aspect-[4/3] overflow-hidden bg-[#eef0f2]">{!failed?<img src={url} alt={`Vehicle photo ${index+1}`} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" onError={()=>setFailedImages(c=>c.includes(url)?c:[...c,url])}/>:<div className="flex h-full flex-col items-center justify-center gap-2 text-[#9ca3af]"><ImageIcon size={24}/><span className="text-[11px]">Image unavailable</span></div>}<div className="absolute inset-x-0 top-0 flex justify-between p-3"><span className="rounded-lg bg-black/75 px-2.5 py-1.5 text-[10px] font-bold text-white">{String(index+1).padStart(2,'0')}</span>{index===0&&<span className="inline-flex items-center gap-1 rounded-lg bg-[#16A6B8] px-2.5 py-1.5 text-[10px] font-bold text-white"><Star size={11} className="fill-current"/> Lead photo</span>}</div><div className="absolute inset-x-0 bottom-0 flex justify-between bg-gradient-to-t from-black/70 to-transparent p-3 pt-10 opacity-0 transition group-hover:opacity-100 focus-within:opacity-100"><div className="flex gap-1.5"><button type="button" disabled={index===0} onClick={()=>move(index,-1)} className="flex h-9 w-9 items-center justify-center rounded-lg bg-white text-[#374151] disabled:opacity-40"><ArrowUp size={15}/></button><button type="button" disabled={index===value.length-1} onClick={()=>move(index,1)} className="flex h-9 w-9 items-center justify-center rounded-lg bg-white text-[#374151] disabled:opacity-40"><ArrowDown size={15}/></button></div><button type="button" onClick={()=>remove(index)} className="flex h-9 w-9 items-center justify-center rounded-lg bg-white text-red-600"><Trash2 size={15}/></button></div></div><div className="p-4"><div className="flex items-center justify-between gap-2"><div><p className="text-xs font-bold text-[#374151]">{index===0?'Primary vehicle photo':`Gallery photo ${index+1}`}</p><p title={url} className="mt-1 truncate font-mono text-[10px] text-[#9ca3af]">{url}</p></div><GripVertical size={14} className="text-[#c4c9cf]"/></div></div></article>})}</div>}
    {value.length>0&&<div className="flex items-center gap-2 text-[11px] text-[#9ca3af]"><GripVertical size={13}/><span>Use the arrows to arrange the gallery. Photo 01 is automatically the lead image.</span></div>}
    <input type="hidden" name="galleryUrls" value={value.join('\n')} readOnly />
  </div>
}
