import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, CalendarDays, ChevronRight } from 'lucide-react';

const articles = [
  { title: '8 reasons why you should buy your car from ICar Gezina', category: 'Buying Guide', date: 'Buying advice', image: '/SUVs.png', copy: 'From quality pre-owned vehicles to friendly service, discover what makes the ICar Gezina buying experience different.' },
  { title: 'How to choose the right car for your lifestyle', category: 'Buying Guide', date: 'Car advice', image: '/Coupes.png', copy: 'SUV, coupe, bakkie or hatchback? A practical guide to choosing a vehicle that fits the way you live.' },
  { title: 'What documents do you need when selling your car?', category: 'Sell Your Car', date: 'Helpful guide', image: '/Bakkies.png', copy: 'Understand the basic paperwork and information you may need when changing ownership or selling your vehicle.' },
  { title: 'Making car finance simple', category: 'Finance', date: 'Finance guide', image: '/Hatchbacks.png', copy: 'Learn what to prepare for a vehicle finance application and how our team can help you through the process.' },
  { title: 'Looking after your car after purchase', category: 'After Sales', date: 'Ownership tips', image: '/SUVs.png', copy: 'Simple habits and checks that can help you keep your vehicle reliable, safe and enjoyable for longer.' },
  { title: 'Questions to ask before buying a pre-owned vehicle', category: 'Buying Guide', date: 'Buyer checklist', image: '/Coupes.png', copy: 'Use these practical questions to compare vehicles confidently and make a more informed purchase.' },
];

const categories = ['All', 'Buying Guide', 'Finance', 'Sell Your Car', 'After Sales'];

export default function ArticlesPage() {
  return (
    <div className="bg-[#242424] text-white">
      <section className="relative overflow-hidden border-b border-white/10 bg-[#181818] pt-28 sm:pt-32"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(22,166,184,0.18),transparent_30%),radial-gradient(circle_at_20%_80%,rgba(242,138,46,0.12),transparent_28%)]" /><div className="relative mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28"><p className="text-[10px] font-bold uppercase tracking-[0.32em] text-[#F28A2E]">ICar Gezina Journal</p><h1 className="mt-4 max-w-4xl text-5xl font-black leading-[0.95] tracking-[-0.04em] sm:text-6xl lg:text-8xl">Advice for the road <span className="text-[#16A6B8]">ahead.</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-white/50 sm:text-lg">Helpful guides, buying advice, finance information and ownership tips from the ICar Gezina team.</p></div></section>

      <section className="border-b border-white/10 bg-[#2b2b2b]"><div className="mx-auto flex max-w-7xl gap-2 overflow-x-auto px-4 py-5 sm:px-6 lg:px-8">{categories.map((category, index) => <button key={category} type="button" className={`whitespace-nowrap rounded-full px-5 py-2.5 text-xs font-bold transition ${index === 0 ? 'bg-[#16A6B8] text-white' : 'border border-white/10 text-white/55 hover:border-[#16A6B8]/60 hover:text-white'}`}>{category}</button>)}</div></section>

      <section className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-10 flex items-end justify-between gap-6"><div><p className="text-[10px] font-bold uppercase tracking-[0.28em] text-[#F28A2E]">Latest articles</p><h2 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">From the ICar Gezina team.</h2></div><Link href="/cars" className="hidden items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-[#16A6B8] sm:inline-flex">Browse vehicles <ArrowRight className="h-4 w-4" /></Link></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{articles.map((article, index) => <article key={article.title} className="group overflow-hidden rounded-2xl border border-white/10 bg-[#2b2b2b] transition duration-300 hover:-translate-y-1 hover:border-white/20 hover:shadow-2xl"><div className="relative aspect-[16/10] overflow-hidden bg-[#303030]"><Image src={article.image} alt="" fill sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-contain p-4 transition duration-500 group-hover:scale-105" /><span className="absolute left-4 top-4 rounded-full bg-[#181818]/90 px-3 py-1.5 text-[9px] font-bold uppercase tracking-[0.16em] text-[#F28A2E]">{article.category}</span></div><div className="p-6"><div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.12em] text-white/30"><CalendarDays className="h-3.5 w-3.5" />{article.date}</div><h3 className="mt-4 text-xl font-bold leading-tight transition group-hover:text-[#16A6B8]">{article.title}</h3><p className="mt-3 text-sm leading-6 text-white/45">{article.copy}</p><Link href="/contact" className="mt-6 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-[#16A6B8]">Read more <ChevronRight className="h-4 w-4 transition group-hover:translate-x-1" /></Link></div></article>)}</div></div></section>

      <section className="bg-[#303030] py-16"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-4 sm:px-6 lg:flex-row lg:items-center lg:justify-between lg:px-8"><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#F28A2E]">Need help choosing?</p><h2 className="mt-2 text-3xl font-black">Talk to the ICar Gezina team.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-white/45">If you have questions about a vehicle, finance or the buying process, we are ready to help.</p></div><div className="flex flex-wrap gap-3"><Link href="/cars" className="inline-flex items-center gap-2 rounded-full bg-[#16A6B8] px-6 py-3 text-xs font-bold uppercase tracking-[0.12em]">View showroom <ArrowRight className="h-4 w-4" /></Link><Link href="/contact" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-6 py-3 text-xs font-bold uppercase tracking-[0.12em] text-white/75 hover:border-white/30 hover:text-white">Contact us</Link></div></div></section>
    </div>
  );
}
