import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, BadgeCheck, Banknote, CheckCircle2, FileText, ShieldCheck } from 'lucide-react';

const steps = [
  { number: '01', title: 'Choose your vehicle', copy: 'Browse our showroom and find the vehicle that fits your budget and lifestyle.' },
  { number: '02', title: 'Complete your application', copy: 'Give us a few details and our team will guide you through the finance application.' },
  { number: '03', title: 'Get a decision', copy: 'We work with trusted finance partners to help make the process simple and straightforward.' },
  { number: '04', title: 'Drive away happy', copy: 'Once approved and everything is finalised, we help you get behind the wheel.' },
];
const requirements = ['South African ID or valid identification', 'Latest proof of income', 'Latest proof of residential address', 'Three months bank statements where required'];

export default function FinancePage() {
  return <div className="bg-[#282828] text-white">
    <section className="relative isolate overflow-hidden border-b border-white/10 bg-[#171717]">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_18%,rgba(232,117,26,0.28),transparent_34%),radial-gradient(circle_at_12%_90%,rgba(0,114,188,0.2),transparent_38%)]" />
      <div className="absolute right-[-10%] top-[-25%] h-[620px] w-[620px] rounded-full border border-[#E8751A]/10" /><div className="absolute bottom-0 left-0 h-1 w-full bg-gradient-to-r from-[#E8751A] via-[#E8751A] to-[#0072BC]" />
      <div className="relative mx-auto flex min-h-[600px] max-w-7xl items-center px-4 py-24 sm:px-6 lg:min-h-[680px] lg:px-8">
        <div className="max-w-4xl"><span className="inline-flex rounded-full border border-[#E8751A]/40 bg-[#E8751A]/10 px-4 py-2 text-xs font-bold uppercase tracking-[0.25em] text-[#E8751A]">ICar Gezina Finance</span><h1 className="mt-6 text-5xl font-black uppercase italic leading-[0.92] tracking-tight sm:text-6xl lg:text-8xl">Your next car.<br /><span className="text-[#E8751A]">Your way.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300 sm:text-xl">Make the journey to your next vehicle easier with guided finance support from the ICar Gezina team and trusted finance partners.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="#application" className="inline-flex items-center gap-2 rounded-lg bg-[#E8751A] px-7 py-4 text-xs font-bold uppercase tracking-[0.12em] text-white transition hover:-translate-y-0.5 hover:bg-[#d76712]">Apply for finance <ArrowRight className="h-4 w-4" /></Link><Link href="/cars" className="inline-flex items-center gap-2 rounded-lg border border-white/20 px-7 py-4 text-xs font-bold uppercase tracking-[0.12em] text-white/80 transition hover:border-[#0072BC]/70 hover:text-white">Browse vehicles</Link></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-xs font-semibold uppercase tracking-[0.12em] text-white/45"><span>Guided application</span><span>Trusted partners</span><span>Personal support</span></div></div>
      </div>
    </section>
    <section className="border-y border-white/10 bg-[#303030] py-14"><div className="mx-auto grid max-w-7xl gap-5 px-4 sm:grid-cols-3 sm:px-6 lg:px-8"><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><Banknote className="h-6 w-6 text-[#E8751A]" /><h2 className="mt-5 text-lg font-bold">Easy finance</h2><p className="mt-2 text-sm leading-6 text-white/45">We make the finance journey clear, with friendly guidance from application to approval.</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><BadgeCheck className="h-6 w-6 text-[#0072BC]" /><h2 className="mt-5 text-lg font-bold">Trusted process</h2><p className="mt-2 text-sm leading-6 text-white/45">Our team works with established finance partners to help find a suitable solution.</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><ShieldCheck className="h-6 w-6 text-white/80" /><h2 className="mt-5 text-lg font-bold">Personal support</h2><p className="mt-2 text-sm leading-6 text-white/45">You are never left to figure it out alone. We explain each step before you proceed.</p></div></div></section>
    <section className="bg-[#282828] py-20 sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-[10px] font-bold uppercase tracking-[0.28em] text-[#E8751A]">How it works</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Finance made simple.</h2><p className="mt-4 text-sm leading-7 text-white/45 sm:text-base">From choosing your vehicle to completing the paperwork, our team is here to keep things moving.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-4">{steps.map(step => <div key={step.number} className="bg-[#292929] p-7"><span className="text-xs font-bold tracking-[0.2em] text-[#E8751A]">{step.number}</span><h3 className="mt-8 text-xl font-bold">{step.title}</h3><p className="mt-3 text-sm leading-6 text-white/45">{step.copy}</p></div>)}</div></div></section>
    <section id="application" className="bg-[#303030] py-20 sm:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div><p className="text-[10px] font-bold uppercase tracking-[0.28em] text-[#E8751A]">Start your application</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Let&apos;s get you moving.</h2><p className="mt-5 text-sm leading-7 text-white/50">Complete the details below and our finance team can contact you about your application and next steps.</p><div className="mt-8 space-y-3">{requirements.map(item => <div key={item} className="flex items-start gap-3 text-sm text-white/65"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#0072BC]" />{item}</div>)}</div></div><form className="rounded-3xl border border-white/10 bg-[#202020] p-6 shadow-2xl sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-xs font-semibold text-white/65">Full name<input name="name" required className="mt-2 h-12 w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 text-sm text-white outline-none transition focus:border-[#0072BC]" /></label><label className="text-xs font-semibold text-white/65">Phone number<input name="phone" required type="tel" className="mt-2 h-12 w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 text-sm text-white outline-none transition focus:border-[#0072BC]" /></label><label className="text-xs font-semibold text-white/65">Email address<input name="email" required type="email" className="mt-2 h-12 w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 text-sm text-white outline-none transition focus:border-[#0072BC]" /></label><label className="text-xs font-semibold text-white/65">Employment status<select name="employment" className="mt-2 h-12 w-full rounded-xl border border-white/10 bg-[#202020] px-4 text-sm text-white/70 outline-none focus:border-[#0072BC]"><option>Employed</option><option>Self-employed</option><option>Other</option></select></label><label className="text-xs font-semibold text-white/65 sm:col-span-2">Vehicle of interest<input name="vehicle" placeholder="e.g. BMW X3" className="mt-2 h-12 w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 text-sm text-white outline-none transition placeholder:text-white/25 focus:border-[#0072BC]" /></label></div><button type="submit" className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#E8751A] px-6 py-4 text-xs font-bold uppercase tracking-[0.14em] transition hover:bg-[#d76712]">Submit finance enquiry <ArrowRight className="h-4 w-4" /></button><p className="mt-4 text-center text-[11px] leading-5 text-white/30">Submitting this form does not guarantee finance approval. Final approval is subject to the relevant lender&apos;s assessment and terms.</p></form></div></section>
    <section className="bg-[#282828] py-16"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-4 sm:px-6 lg:flex-row lg:items-center lg:justify-between lg:px-8"><div><FileText className="h-6 w-6 text-[#E8751A]" /><h2 className="mt-4 text-2xl font-black">Already know what you want?</h2><p className="mt-2 text-sm text-white/45">Find a vehicle and start your journey today.</p></div><Link href="/cars" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-6 py-3 text-xs font-bold uppercase tracking-[0.12em] hover:border-[#0072BC] hover:text-[#0072BC]">Explore the showroom <ArrowRight className="h-4 w-4" /></Link></div></section>
  </div>;
}
